import "./globals.css";

export const metadata = {
  title: "F1 Dashboard",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    /* The 'suppressHydrationWarning' below tells React to ignore 
      changes made by browser extensions (like LanguageTool), 
      fixing the error you saw.
    */
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}